version: '2'
services:
  reacttestapp2-app:
    image: reacttestapp2
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://reacttestapp2-mysql:3306/reacttestapp2?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://reacttestapp2-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://reacttestapp2-elasticsearch:9200
    ports:
      - 8080:8080
  reacttestapp2-mysql:
    extends:
      file: mysql.yml
      service: reacttestapp2-mysql
  reacttestapp2-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: reacttestapp2-elasticsearch
